server:
  port: 8082
spring:
  application:
    name: rabbitmq-springboot

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ale
    password: 123456
    virtual-host: /test
    template:
      retry:
        enabled: true
    listener:
      simple:
        acknowledge-mode: manual  # 开启消费者手动 ack
        type: simple
    # 消息 exchange->queue 失败回调
    publisher-returns: true
    # 消息 producer->exchange 确认机制 是否需要回调
    publisher-confirm-type: correlated

logging:
  level:
    root: info

